### ISSUE TITLE
Spawning random fakeplayer

### ISSUE THREAD

**Issue by IonicSyz1823** [David-pm-pl/GhostPlayer#4]
It would be nice if you can implement a command /ghostplayer spawn random to spawn a random fakeplayer instead of a specific one

**Comment by DavidGlitch04** [comment]
Dear @IonicSyz1823,
> Your suggestion has been accepted.
GhostPlayer v0.0.2 has improve please download [it here](https://github.com/David-pm-pl/GhostPlayer/releases/tag/v0.0.2)
